# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

name: 'graphql'

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.402' # replace this value with the version that you need for your project

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom' # Options: build, push, pack, publish, restore, run, test, custom
    custom: 'tool'
    arguments: 'install -g Cake.Tool'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom' # Options: build, push, pack, publish, restore, run, test, custom
    custom: 'cake'
    arguments: 'build.cake'